export type GetForwardResponse = {
  alias: string;
  channelDbId: number;
  lndChannelPoint: string;
  pub_key: string;
  shortChannelId: string;
  chan_id: number;
  color: string;
  open: number;
  capacity: number;
  amount_out: number;
  amount_in: number;
  amount_total: number;
  revenue_out: number;
  revenue_in: number;
  revenue_total: number;
  count_out: number;
  count_in: number;
  count_total: number;
  turnover_out: number;
  turnover_in: number;
  turnover_total: number;
};
