export type Forward = {
  alias: string;
  fundingTransactionHash: string;
  fundingOutputIndex: number;
  pubKey: string;
  shortChannelId: string;
  channelId: number;
  color: string;
  statusId: number;
  capacity: number;
  amountIn: number;
  amountOut: number;
  amountTotal: number;
  revenueIn: number;
  revenueOut: number;
  revenueTotal: number;
  countIn: number;
  countOut: number;
  countTotal: number;
  turnoverIn: number;
  turnoverOut: number;
  turnoverTotal: number;
};
