// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go


import { ColumnMetaData } from "features/table/types";
import { ChannelPending } from "features/channelsPending/channelsPendingTypes";

export const AllChannelPendingColumns: ColumnMetaData<ChannelPending>[] = [
	{
		heading: "Peer Alias",
		type: "AliasCell",
		key: "peerAlias",
		valueType: "string",
		locked: true,
	},
	{
		heading: "Short Channel ID",
		type: "LongTextCell",
		key: "shortChannelId",
		valueType: "string",
	},
	{
		heading: "Capacity",
		type: "NumericCell",
		key: "capacity",
		valueType: "number",
	},
	{
		heading: "Fee rate (PPM)",
		type: "NumericDoubleCell",
		key: "feeRateMilliMsat",
		valueType: "number",
		key2: "remoteFeeRateMilliMsat",
	},
	{
		heading: "Base Fee",
		type: "NumericDoubleCell",
		key: "feeBase",
		valueType: "number",
		key2: "remoteFeeBase",
	},
	{
		heading: "Remote Fee rate (PPM)",
		type: "NumericCell",
		key: "remoteFeeRateMilliMsat",
		valueType: "number",
	},
	{
		heading: "Remote Base Fee",
		type: "NumericCell",
		key: "remoteFeeBase",
		valueType: "number",
	},
	{
		heading: "LND Short Channel ID",
		type: "LongTextCell",
		key: "lndShortChannelId",
		valueType: "string",
	},
	{
		heading: "Funding Transaction",
		type: "LongTextCell",
		key: "fundingTransactionHash",
		valueType: "string",
	},
	{
		heading: "Funding BlockHeight",
		type: "NumericCell",
		key: "fundingBlockHeight",
		valueType: "number",
	},
	{
		heading: "Funding BlockHeight Delta",
		type: "NumericCell",
		key: "fundingBlockHeightDelta",
		valueType: "number",
	},
	{
		heading: "Funding Date",
		type: "DateCell",
		key: "fundedOn",
		valueType: "date",
	},
	{
		heading: "Funding Date Delta (Seconds)",
		type: "DurationCell",
		key: "fundedOnSecondsDelta",
		valueType: "duration",
	},
	{
		heading: "Closing Transaction",
		type: "LongTextCell",
		key: "closingTransactionHash",
		valueType: "string",
	},
	{
		heading: "Closing BlockHeight",
		type: "NumericCell",
		key: "closingBlockHeight",
		valueType: "number",
	},
	{
		heading: "Closing BlockHeight Delta",
		type: "NumericCell",
		key: "closingBlockHeightDelta",
		valueType: "number",
	},
	{
		heading: "Node Name",
		type: "TextCell",
		key: "nodeName",
		valueType: "string",
	},
	{
		heading: "Status",
		type: "TextCell",
		key: "status",
		valueType: "enum",
	},
];


// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go

export const ChannelsPendingSortableColumns: Array<keyof ChannelPending> = [
	"peerAlias",
	"shortChannelId",
	"capacity",
	"feeRateMilliMsat",
	"feeBase",
	"remoteFeeRateMilliMsat",
	"remoteFeeBase",
	"lndShortChannelId",
	"fundingTransactionHash",
	"fundingBlockHeight",
	"fundingBlockHeightDelta",
	"fundedOn",
	"fundedOnSecondsDelta",
	"closingTransactionHash",
	"closingBlockHeight",
	"closingBlockHeightDelta",
	"nodeName",
	"status",
];


// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go

export const ChannelsPendingFilterableColumns: Array<keyof ChannelPending> = [
	"peerAlias",
	"shortChannelId",
	"capacity",
	"feeRateMilliMsat",
	"feeBase",
	"remoteFeeRateMilliMsat",
	"remoteFeeBase",
	"lndShortChannelId",
	"fundingTransactionHash",
	"fundingBlockHeight",
	"fundingBlockHeightDelta",
	"fundedOn",
	"fundedOnSecondsDelta",
	"closingTransactionHash",
	"closingBlockHeight",
	"closingBlockHeightDelta",
	"nodeName",
	"status",
];