// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go


import { ColumnMetaData } from "features/table/types";
import { OnChainTx } from "features/transact/OnChain/types";

export const AllOnChainTransactionsColumns: ColumnMetaData<OnChainTx>[] = [
	{
		heading: "Date",
		type: "DateCell",
		key: "date",
		valueType: "date",
	},
	{
		heading: "Amount",
		type: "NumericCell",
		key: "amount",
		valueType: "number",
	},
	{
		heading: "Fees",
		type: "NumericCell",
		key: "totalFees",
		valueType: "number",
	},
	{
		heading: "Tx Hash",
		type: "LongTextCell",
		key: "txHash",
		valueType: "string",
	},
	{
		heading: "LND Short Channel ID",
		type: "LongTextCell",
		key: "lndShortChanId",
		valueType: "string",
	},
	{
		heading: "LND Tx type label",
		type: "LongTextCell",
		key: "lndTxTypeLabel",
		valueType: "string",
	},
	{
		heading: "Destination Addresses Count",
		type: "NumericCell",
		key: "destAddressesCount",
		valueType: "number",
	},
	{
		heading: "Label",
		type: "TextCell",
		key: "label",
		valueType: "string",
	},
];


// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go

export const OnChainTransactionsSortableColumns: Array<keyof OnChainTx> = [
	"date",
	"amount",
	"totalFees",
	"lndShortChanId",
	"lndTxTypeLabel",
	"destAddressesCount",
	"label",
];