// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go


import { ColumnMetaData } from "features/table/types";
import { ExpandedTag } from "pages/tags/tagsTypes";

export const AllTagsColumns: ColumnMetaData<ExpandedTag>[] = [
	{
		heading: "Name",
		type: "TextCell",
		key: "name",
		valueType: "string",
	},
	{
		heading: "Category",
		type: "TextCell",
		key: "categoryId",
		valueType: "string",
	},
	{
		heading: "Applied to",
		type: "NumericCell",
		key: "channels",
		valueType: "string",
	},
	{
		heading: "Edit",
		type: "EditCell",
		key: "edit",
		valueType: "string",
	},
	{
		heading: "Delete",
		type: "EditCell",
		key: "delete",
		valueType: "string",
	},
];


// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go

export const TagsSortableColumns: Array<keyof ExpandedTag> = [
];