// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go


import { ColumnMetaData } from "features/table/types";
import { Payment } from "features/transact/Payments/types";

export const AllPaymentsColumns: ColumnMetaData<Payment>[] = [
	{
		heading: "Date",
		type: "DateCell",
		key: "date",
		valueType: "date",
	},
	{
		heading: "Status",
		type: "TextCell",
		key: "status",
		valueType: "array",
	},
	{
		heading: "Value",
		type: "NumericCell",
		key: "value",
		valueType: "number",
	},
	{
		heading: "Fee",
		type: "NumericCell",
		key: "fee",
		valueType: "number",
	},
	{
		heading: "PPM",
		type: "NumericCell",
		key: "ppm",
		valueType: "number",
	},
	{
		heading: "Rebalance",
		type: "BooleanCell",
		key: "isRebalance",
		valueType: "boolean",
	},
	{
		heading: "Seconds In Flight",
		type: "DurationCell",
		key: "secondsInFlight",
		valueType: "duration",
	},
	{
		heading: "Failure Reason",
		type: "TextCell",
		key: "failureReason",
		valueType: "array",
	},
	{
		heading: "MPP",
		type: "BooleanCell",
		key: "isMpp",
		valueType: "boolean",
	},
	{
		heading: "Failed Attempts",
		type: "NumericCell",
		key: "countFailedAttempts",
		valueType: "number",
	},
	{
		heading: "Successful Attempts",
		type: "NumericCell",
		key: "countSuccessfulAttempts",
		valueType: "number",
	},
	{
		heading: "Destination",
		type: "LongTextCell",
		key: "destinationPubKey",
		valueType: "string",
	},
	{
		heading: "Payment Hash",
		type: "TextCell",
		key: "paymentHash",
		valueType: "string",
	},
	{
		heading: "Payment Preimage",
		type: "TextCell",
		key: "paymentPreimage",
		valueType: "string",
	},
];


// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go

export const PaymentsSortableColumns: Array<keyof Payment> = [
	"date",
	"status",
	"value",
	"fee",
	"ppm",
	"isRebalance",
	"secondsInFlight",
	"failureReason",
	"countFailedAttempts",
	"countSuccessfulAttempts",
];