// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go


import { ColumnMetaData } from "features/table/types";
import { Payment } from "features/transact/Payments/types";

export const AllPaymentsColumns: ColumnMetaData<Payment>[] = [
	{
		heading: "Date",
		type: "DateCell",
		key: "date",
		valueType: "date",
	},
	{
		heading: "Status",
		type: "TextCell",
		key: "status",
		valueType: "array",
		selectOptions: [
			{ label: "Succeeded", value: "SUCCEEDED" },
			{ label: "In Flight", value: "IN_FLIGHT" },
			{ label: "Failed", value: "FAILED" },
		],
	},
	{
		heading: "Value",
		type: "NumericCell",
		key: "value",
		valueType: "number",
	},
	{
		heading: "Fee",
		type: "NumericCell",
		key: "fee",
		valueType: "number",
	},
	{
		heading: "PPM",
		type: "NumericCell",
		key: "ppm",
		valueType: "number",
	},
	{
		heading: "Rebalance",
		type: "BooleanCell",
		key: "isRebalance",
		valueType: "boolean",
	},
	{
		heading: "Seconds In Flight",
		type: "DurationCell",
		key: "secondsInFlight",
		valueType: "duration",
	},
	{
		heading: "Failure Reason",
		type: "TextCell",
		key: "failureReason",
		valueType: "array",
		selectOptions: [
			{ label: "None", value: "FAILURE_REASON_NONE" },
			{ label: "Timeout", value: "FAILURE_REASON_TIMEOUT" },
			{ label: "No Route", value: "FAILURE_REASON_NO_ROUTE" },
			{ label: "Error", value: "FAILURE_REASON_ERROR" },
			{ label: "Incorrect Payment Details", value: "FAILURE_REASON_INCORRECT_PAYMENT_DETAILS" },
			{ label: "Incorrect Payment Amount", value: "FAILURE_REASON_INCORRECT_PAYMENT_AMOUNT" },
			{ label: "Payment Hash Mismatch", value: "FAILURE_REASON_PAYMENT_HASH_MISMATCH" },
			{ label: "Incorrect Payment Request", value: "FAILURE_REASON_INCORRECT_PAYMENT_REQUEST" },
			{ label: "Unknown", value: "FAILURE_REASON_UNKNOWN" },
		],
	},
	{
		heading: "MPP",
		type: "BooleanCell",
		key: "isMpp",
		valueType: "boolean",
	},
	{
		heading: "Failed Attempts",
		type: "NumericCell",
		key: "countFailedAttempts",
		valueType: "number",
	},
	{
		heading: "Successful Attempts",
		type: "NumericCell",
		key: "countSuccessfulAttempts",
		valueType: "number",
	},
	{
		heading: "Destination",
		type: "LongTextCell",
		key: "destinationPubKey",
		valueType: "string",
	},
	{
		heading: "Payment Hash",
		type: "TextCell",
		key: "paymentHash",
		valueType: "string",
	},
	{
		heading: "Payment Preimage",
		type: "TextCell",
		key: "paymentPreimage",
		valueType: "string",
	},
];


// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go

export const PaymentsSortableColumns: Array<keyof Payment> = [
	"date",
	"status",
	"value",
	"fee",
	"ppm",
	"isRebalance",
	"secondsInFlight",
	"failureReason",
	"countFailedAttempts",
	"countSuccessfulAttempts",
];


// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go

export const PaymentsFilterableColumns: Array<keyof Payment> = [
	"date",
	"status",
	"value",
	"fee",
	"ppm",
	"isRebalance",
	"secondsInFlight",
	"failureReason",
	"isMpp",
	"countFailedAttempts",
	"countSuccessfulAttempts",
	"destinationPubKey",
	"paymentHash",
	"paymentPreimage",
];