import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { ColumnMetaData } from "features/table/types";
import { RootState } from "store/store";
import { torqApi } from "apiSlice";

// export interface TableInvoiceState {
//   invoiceViews: ViewInterface<Invoice>[];
//   selectedViewIndex: number;
// }

//
// const initialState: TableInvoiceState = {
//   selectedViewIndex: 0,
//   invoiceViews: [
//     {
//       ...DefaultView,
//       title: "Default View",
//     },
//   ],
// };
//
// export const invoicesSlice = createSlice({
//   name: "invoices",
//   initialState,
//   reducers: {
//     updateInvoicesFilters: (state, actions: PayloadAction<{ filters: any }>) => {
//       state.invoiceViews[0].filters = actions.payload.filters;
//     },
//     updateColumns: (state, actions: PayloadAction<{ columns: ColumnMetaData<Invoice>[] }>) => {
//       state.invoiceViews[0].columns = actions.payload.columns;
//     },
//     updateViews: (state, actions: PayloadAction<{ views: ViewInterface<Invoice>[]; index: number }>) => {
//       state.invoiceViews = actions.payload.views;
//       state.selectedViewIndex = actions.payload.index;
//     },
//     updateViewsOrder: (state, actions: PayloadAction<{ views: ViewInterface<Invoice>[]; index: number }>) => {
//       state.invoiceViews = actions.payload.views;
//       state.selectedViewIndex = actions.payload.index;
//     },
//     deleteView: (state, actions: PayloadAction<{ view: ViewInterface<Invoice>; index: number }>) => {
//       state.invoiceViews = [
//         ...state.invoiceViews.slice(0, actions.payload.index),
//         ...state.invoiceViews.slice(actions.payload.index + 1, state.invoiceViews.length),
//       ];
//       state.selectedViewIndex = 0;
//     },
//     updateSelectedView: (state, actions: PayloadAction<{ index: number }>) => {
//       state.selectedViewIndex = actions.payload.index;
//     },
//   },
//   // The `extraReducers` field lets the slice handle actions defined elsewhere,
//   // including actions generated by createAsyncThunk or in other slices.
//   extraReducers: (builder) => {
//     builder.addMatcher(
//       (action) => {
//         return (
//           ["invoices/updateInvoicesFilters", "invoices/updateColumns"].findIndex((item) => action.type === item) !== -1
//         );
//       },
//       (state, _) => {
//         state.invoiceViews[state.selectedViewIndex].saved = false;
//       }
//     );
//
//     builder.addMatcher(torqApi.endpoints.createTableView.matchFulfilled, (state, { payload }) => {
//       state.invoiceViews[payload.index] = {
//         ...payload.view.view,
//         id: payload.view.id,
//       };
//       state.selectedViewIndex = payload.index;
//     });
//
//     builder.addMatcher(torqApi.endpoints.deleteTableView.matchFulfilled, (state, { payload }) => {
//       state.invoiceViews = [
//         ...state.invoiceViews.slice(0, payload.index),
//         ...state.invoiceViews.slice(payload.index + 1, state.invoiceViews.length),
//       ];
//       state.selectedViewIndex = 0;
//     });
//
//     builder.addMatcher(torqApi.endpoints.getTableViews.matchFulfilled, (state, { payload }) => {
//       if (payload !== null) {
//         state.invoiceViews = payload.map((view: { id: number; view: ViewInterface<Invoice> }) => {
//           return { ...view.view, id: view.id };
//         });
//       }
//     });
//
//     builder.addMatcher(torqApi.endpoints.updateTableView.matchFulfilled, (state, { payload }) => {
//       const view = state.invoiceViews.find((v) => v.id === payload.id);
//       if (view) {
//         view.saved = true;
//       }
//     });
//   },
// });
//
// export const { updateInvoicesFilters, updateColumns, updateViews, updateViewsOrder, deleteView, updateSelectedView } =
//   invoicesSlice.actions;
//
// export const selectInvoicesFilters = (state: { invoices: TableInvoiceState }) => {
//   return state.invoices.invoiceViews[state.invoices.selectedViewIndex].filters;
// };
//
// export const selectActiveColumns = (state: { invoices: TableInvoiceState }) => {
//   return state.invoices.invoiceViews[state.invoices.selectedViewIndex].columns || [];
// };
//
// export const selectAllColumns = (_: { invoices: TableInvoiceState }) => AllInvoicesColumns;
// export const selectViews = (state: { invoices: TableInvoiceState }) => state.invoices.invoiceViews;
// export const selectCurrentView = (state: { invoices: TableInvoiceState }) =>
//   state.invoices.invoiceViews[state.invoices.selectedViewIndex];
// export const selectedViewIndex = (state: { invoices: TableInvoiceState }) => state.invoices.selectedViewIndex;
//
// export default invoicesSlice.reducer;
