// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go

import { ColumnMetaData } from "features/table/types";
import { Peer } from "features/peers/peersTypes";

export const AllPeersColumns: ColumnMetaData<Peer>[] = [
  {
    heading: "Public key",
    type: "LongTextCell",
    key: "pubKey",
    valueType: "string",
  },
  {
    heading: "Chain",
    type: "TextCell",
    key: "chain",
    valueType: "enum",
    selectOptions: [{ label: "Bitcoin", value: "Bitcoin" }],
  },
  {
    heading: "Network",
    type: "TextCell",
    key: "network",
    valueType: "enum",
    selectOptions: [
      { label: "MainNet", value: "MainNet" },
      { label: "TestNet", value: "TestNet" },
      { label: "RegTest", value: "RegTest" },
      { label: "SigNet", value: "SigNet" },
      { label: "SimNet", value: "SimNet" },
    ],
  },
];

// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go

export const PeersSortableColumns: Array<keyof Peer> = [];

// DO NOT EDIT THIS FILE...
// This File is generated by go:generate
// For more information look at cmd/torq/gen.go

export const PeersFilterableColumns: Array<keyof Peer> = [];
